### PR TITLE
Do not render when the Revit view is not ThreeD

### PR DESCRIPTION
**Pull request by MingboPeng**

### CODE REVIEW

**Comment by kike-garbo** [comment]
Hi,

I'm looking your PR and see you are trying to disable the Grasshopper preview in 2D views.
Is the preview annoying in that case?

**Comment by MingboPeng** [comment]
Hi @kike-garbo,
Thanks for checking.
Render objects in views (2D, Section, Schedule, etc) other than 3D, constantly crashes the revit. I haven't really dived into which specific type of object causing it, or it is just because of the revit view type (I mean 2D plan view here).
But generally, it makes sense not to render objects in view types like "schedule" or "sheet", etc.

Please let me know if this makes sense.
Mingbo

**Comment by kike-garbo** [comment]
There use to be a bug before 2019-04-11 that may cause those crashes on Cropped Views.
2D Views use to be cropped so maybe is the relation you found betwen 2D Views and crashes.

Could you please check if you have updated your repository since then?
If you have updated can I have access to a file that provoques this crash?

**Comment by MingboPeng** [comment]
Hi @kike-garbo, thanks. I have found where the issue is. It is because the Rhino geometry is not checked for if it is valid before rendering it to Revit. 
This is the fix: https://github.com/mcneel/rhino.inside/pull/88/commits/9af554e78489ffa9d13351f45258d7a9b6bf849d

**Comment by kike-garbo** [comment]
Thanks!!

Do you know any fast trick to have invalid geometry in Grasshopper?
Just to test your PR.

**Comment by MingboPeng** [comment]
@kike-garbo  you can do a line with the same start and end point.

**Pull request merged**
